import jsPDF from "jspdf";
import "jspdf-autotable";

export const generatePDF = (data, result) => {
  const doc = new jsPDF();

  // --- 1. KOP SURAT (HEADER) ---
  // Warna Teal PLN
  doc.setFillColor(27, 122, 143); // #1B7A8F
  doc.rect(0, 0, 210, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("LAPORAN ANALISIS DGA", 105, 18, { align: "center" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("PT. PLN (PERSERO) UPT MANADO", 105, 26, { align: "center" });
  doc.text("Generated by PLN Smart-Trafo System", 105, 32, { align: "center" });

  // --- 2. INFORMASI TRAFO ---
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.text(`ID / Nama Trafo : ${data.id_trafo || "Tidak Diketahui"}`, 14, 55);
  doc.text(
    `Tanggal Uji       : ${new Date().toLocaleDateString("id-ID", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    })}`,
    14,
    62
  );

  // --- 3. TABEL DATA GAS ---
  doc.autoTable({
    startY: 70,
    head: [["Parameter Gas", "Konsentrasi (ppm)", "Status Limit"]],
    body: [
      ["Hidrogen (H2)", data.h2, data.h2 > 100 ? "TINGGI (>100)" : "Normal"],
      ["Metana (CH4)", data.ch4, data.ch4 > 120 ? "TINGGI (>120)" : "Normal"],
      ["Asetilen (C2H2)", data.c2h2, data.c2h2 > 1 ? "BAHAYA (>1)" : "Normal"],
      ["Etilen (C2H4)", data.c2h4, data.c2h4 > 50 ? "TINGGI (>50)" : "Normal"],
      ["Etana (C2H6)", data.c2h6, data.c2h6 > 65 ? "TINGGI (>65)" : "Normal"],
      [
        "Karbon Monoksida (CO)",
        data.co,
        data.co > 350 ? "TINGGI (>350)" : "Normal",
      ],
      ["Karbon Dioksida (CO2)", data.co2, "-"],
    ],
    theme: "grid",
    headStyles: { fillColor: [27, 122, 143] }, // Teal Header
    styles: { fontSize: 10 },
  });

  // --- 4. HASIL DIAGNOSIS ---
  const finalY = doc.lastAutoTable.finalY + 10;

  doc.setFontSize(14);
  doc.setTextColor(27, 122, 143);
  doc.text("HASIL DIAGNOSIS", 14, finalY);

  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);

  // Kotak Hasil
  doc.setDrawColor(200, 200, 200);
  doc.rect(14, finalY + 5, 180, 40);

  doc.setFont("helvetica", "bold");
  doc.text(`Prediksi AI: ${result.ai_status}`, 20, finalY + 15);
  doc.text(`Status IEEE: ${result.ieee_status}`, 20, finalY + 25);

  doc.setFont("helvetica", "normal");
  doc.text(`Detail: ${result.diagnosis}`, 20, finalY + 35);

  // --- 5. REKOMENDASI ---
  doc.setFontSize(14);
  doc.setTextColor(27, 122, 143);
  doc.text("REKOMENDASI TINDAKAN", 14, finalY + 60);

  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  const rekomendasi = getRecommendation(result.ieee_status, data);
  doc.text(rekomendasi, 14, finalY + 70, { maxWidth: 180 });

  // --- 6. FOOTER ---
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Dokumen ini dihasilkan secara otomatis oleh komputer.", 105, 280, {
    align: "center",
  });

  doc.save(`Laporan_DGA_${data.id_trafo}.pdf`);
};

// Helper untuk Rekomendasi di PDF
const getRecommendation = (status, data) => {
  if (status.includes("Status 3") || data.c2h2 > 10) {
    return "BAHAYA: Segera lakukan pemadaman (Trip) atau kurangi beban secara drastis. Lakukan pengujian elektrik lanjutan (Tahanan Isolasi, Tangen Delta) dan rencanakan purifikasi minyak segera.";
  }
  if (status.includes("Status 2")) {
    return "PERINGATAN: Perpendek interval uji DGA menjadi 1 bulan sekali. Monitor laju kenaikan gas (Gassing Rate). Periksa beban trafo apakah berlebih.";
  }
  return "NORMAL: Lanjutkan pemantauan rutin sesuai jadwal (6 bulan / 1 tahun sekali). Tidak diperlukan tindakan khusus.";
};
